<!DOCTYPE html>
<html lang="th">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>โรคไต ใกล้ตัวเรา</title>
    <link href="https://fonts.googleapis.com/css2?family=Sarabun:wght@300;400;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Sarabun', sans-serif;
            text-align: center;
            background-color: #f0f8ff;
            margin: 0;
            padding: 0;
        }
        .container {
            background: white;
            width: 90%;
            max-width: 400px;
            margin: 30px auto;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
        }
        h2 {
            color: #007acc;
        }
        input {
            padding: 10px;
            margin: 10px 0;
            width: 100%;
            border: 1px solid #ddd;
            border-radius: 5px;
            font-size: 16px;
        }
        button {
            background: #007acc;
            color: white;
            padding: 12px;
            width: 100%;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            margin-top: 10px;
        }
        button:hover {
            background: #005f99;
        }
        #result {
            margin-top: 20px;
            font-size: 18px;
            font-weight: bold;
            color: green;
            cursor: pointer;
            text-decoration: underline;
            display: none;
        }
        #advice {
            margin-top: 20px;
            font-size: 16px;
            color: #444;
            background: #e6f7ff;
            padding: 10px;
            border-radius: 5px;
            display: none;
        }
    </style>
</head>
<body>

    <div class="container">
        <h2>โรคไต ใกล้ตัวเรา</h2>

        <input type="text" id="name" placeholder="ชื่อ" required>
        <input type="number" id="weight" placeholder="น้ำหนัก (kg)" required>
        <input type="number" id="age" placeholder="อายุ (ปี)" required>
        <input type="number" id="egfr" placeholder="ค่าไต (eGFR)" required>

        <button id="nextButton" onclick="calculateStage()">ถัดไป</button>

        <p id="result" onclick="showAdvice()"></p>
        <p id="advice"></p>
    </div>

    <script>
        function calculateStage() {
            let name = document.getElementById("name").value;
            let weight = parseFloat(document.getElementById("weight").value);
            let age = parseInt(document.getElementById("age").value);
            let egfr = parseFloat(document.getElementById("egfr").value);

            // ตรวจสอบข้อมูล
            if (!name || isNaN(weight) || isNaN(age) || isNaN(egfr) || weight <= 0 || age <= 0 || egfr <= 0) {
                alert("กรุณากรอกข้อมูลให้ครบทุกช่องและตรวจสอบข้อมูลให้ถูกต้อง");
                return;
            }

            let stage = "";
            let advice = "";

            // การคำนวณระยะของโรคไตจากค่า eGFR
            if (egfr >= 90) {
                stage = "ระยะที่ 1 (ไตปกติ)";
                advice = "ดูแลสุขภาพทั่วไป ดื่มน้ำให้เพียงพอ และตรวจสุขภาพประจำปี";
            } else if (egfr >= 60) {
                stage = "ระยะที่ 2 (ไตเริ่มเสื่อม)";
                advice = "ควรลดการบริโภคเกลือ หลีกเลี่ยงอาหารรสเค็ม และควบคุมความดันโลหิต";
            } else if (egfr >= 45) {
                stage = "ระยะที่ 3a (ไตเสื่อมปานกลาง)";
                advice = "ควรลดการบริโภคโปรตีน และหลีกเลี่ยงยาแก้อักเสบที่ไม่จำเป็น";
            } else if (egfr >= 30) {
                stage = "ระยะที่ 3b (ไตเสื่อมรุนแรง)";
                advice = "ต้องควบคุมอาหารอย่างเคร่งครัด ลดโซเดียมและโปรตีน และติดตามแพทย์อย่างสม่ำเสมอ";
            } else if (egfr >= 15) {
                stage = "ระยะที่ 4 (ไตเสื่อมขั้นรุนแรง)";
                advice = "เตรียมตัวสำหรับการบำบัดทดแทนไต เช่น การฟอกไต ควบคุมอาหารอย่างเข้มงวด";
            } else {
                stage = "ระยะที่ 5 (ไตวายเรื้อรัง)";
                advice = "ต้องได้รับการรักษาด้วยการฟอกไตหรือปลูกถ่ายไต";
            }

            // แสดงผลลัพธ์
            document.getElementById("result").innerHTML = `คุณ ${name} อยู่ใน <br> <strong>${stage}</strong>`;
            document.getElementById("result").style.display = "block";
            
            // เมื่อคลิกที่ผลลัพธ์ จะแสดงคำแนะนำ
            document.getElementById("nextButton").style.display = "none"; // ซ่อนปุ่มหลังจากแสดงผล
            document.getElementById("advice").innerHTML = advice;
            document.getElementById("advice").style.display = "block";
        }

        function showAdvice() {
            document.getElementById("advice").style.display = "block";
        }
    </script>

</body>
</html>
